force-app/main/default/objects/WAV_DataLoad_CFG__mdt/WAV_DataLoad_CFG__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata type to configure the WAV_DataLoad_SCH schedulable apex class, used to initiate/update custom Analytics datasets out of SOQL queries.</description>
    <label>WAV_DataLoad_CFG</label>
    <pluralLabel>WAV_DataLoad_CFG</pluralLabel>
</CustomObject>

force-app/main/default/objects/WAV_DataLoad_CFG__mdt/fields/FieldMapping__c.field-meta.xml
<CustomField>
    <fullName>FieldMapping__c</fullName>
    <description>JSON structure listing the mapping of the field names between Analytics DataSet and the source object.</description>
    <label>FieldMapping</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WAV_DataLoad_CFG__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WAV_DataLoad_CFG__mdt/fields/MaxRowsPerFile__c.field-meta.xml
<CustomField>
    <fullName>MaxRowsPerFile__c</fullName>
    <label>MaxRowsPerFile</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WAV_DataLoad_CFG__mdt/fields/MetaJson__c.field-meta.xml
<CustomField>
    <fullName>MetaJson__c</fullName>
    <label>MetaJson</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAV_DataLoad_CFG__mdt/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Operation done on the target dataset (see InsightsExternalData object details)</description>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Overwrite</fullName>
                <default>true</default>
                <label>Overwrite</label>
            </value>
            <value>
                <fullName>Append</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Upsert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WAV_DataLoad_CFG__mdt/fields/OrderBy__c.field-meta.xml
<CustomField>
    <fullName>OrderBy__c</fullName>
    <description>Object field by which the order by should be made in order to support offset management</description>
    <label>OrderBy</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAV_DataLoad_CFG__mdt/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>SOQL query executed to fetch data for the Analytics dataset.</description>
    <label>Query</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/WAV_DataLoad_SCH.cls
/***
* @description		This class enables to load data extracted via SOQL
*					into custom datasets in Analytics.
*					It relies on the WAV_DataLoad_CFG__mdt custom metadata
*					for configuration and requires Analytics JSON dataset
*					metadata files to be loaded as static resources.
* @author P-E GROS
* @date   Nov 2018
*
* Legal Notice
* 
* MIT License
* 
* Copyright (c) 2018 pegros
* 
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
***/

public class WAV_DataLoad_SCH implements Schedulable {

/***
* @description Entry for schedulable trigger.
* @param       context        Schedulable context (if any).
* @Exception   none special.
***/
    public static void execute(SchedulableContext context) {
        
        WAV_DataLoad_CFG__mdt[] datasetList;
        if (Test.isRunningTest()) {
            datasetList = [select DeveloperName
                           from WAV_DataLoad_CFG__mdt
                           where DeveloperName = 'WAV_Test'];
        } else {
            datasetList = [select DeveloperName
                           from WAV_DataLoad_CFG__mdt
                           where isActive__c = true];
        }
        system.debug('execute datasetList fetched / size ' + datasetList.size());
        
        
        for (WAV_DataLoad_CFG__mdt iterDS : datasetList) {
            WAV_DataLoad_SCH.executeSynch(iterDS.DeveloperName);
        }
        system.debug('execute all dataset synch requested ');
    }
        
/***
* @description Launches a queuable process to process a specific dataset import.
* @param       dataSetName        Developer name of the WAV_DataLoad_CFG__mdt record to process.
* @Exception   none special.
***/
    public static void executeSynch(String dataSetName) {
        System.debug('executeSynch for dataset ' + dataSetName);
        
        WAV_DataLoad_CFG__mdt configElt = [ SELECT  DeveloperName, MasterLabel, FieldMapping__c, Operation__c, 
                                                    MaxRowsPerFile__c, MetaJson__c, Query__c, OrderBy__c 
                                            FROM WAV_DataLoad_CFG__mdt
                                            WHERE DeveloperName = :dataSetName ][0];
        system.debug('executeSynch configElt fetched ' + configElt);
        
        WAV_DataLoad_QUE processJob = new WAV_DataLoad_QUE(configElt);
        ID jobID = System.enqueueJob(processJob);
        system.debug('executeSynch processing job launched: ' + jobID);
        
        return;
    }
}